/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.voronoi.Linear');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voronoi.Linear = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.voronoi.Linear, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.voronoi.Linear.displayName = 'proto.voronoi.Linear';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voronoi.Linear.prototype.toObject = function(opt_includeInstance) {
  return proto.voronoi.Linear.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voronoi.Linear} msg The msg instance to transform.
 * @return {!Object}
 */
proto.voronoi.Linear.toObject = function(includeInstance, msg) {
  var f, obj = {
    t0S: jspb.Message.getFieldWithDefault(msg, 1, 0),
    y0: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    dy: +jspb.Message.getFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voronoi.Linear}
 */
proto.voronoi.Linear.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voronoi.Linear;
  return proto.voronoi.Linear.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voronoi.Linear} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voronoi.Linear}
 */
proto.voronoi.Linear.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setT0S(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY0(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voronoi.Linear.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voronoi.Linear.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voronoi.Linear} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.voronoi.Linear.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getT0S();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getY0();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getDy();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional int64 t0_s = 1;
 * @return {number}
 */
proto.voronoi.Linear.prototype.getT0S = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.voronoi.Linear.prototype.setT0S = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional double y0 = 2;
 * @return {number}
 */
proto.voronoi.Linear.prototype.getY0 = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.voronoi.Linear.prototype.setY0 = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double dy = 3;
 * @return {number}
 */
proto.voronoi.Linear.prototype.getDy = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.voronoi.Linear.prototype.setDy = function(value) {
  jspb.Message.setField(this, 3, value);
};


