/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.voronoi.Polygon');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.voronoi.LatLng');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voronoi.Polygon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.voronoi.Polygon.repeatedFields_, null);
};
goog.inherits(proto.voronoi.Polygon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.voronoi.Polygon.displayName = 'proto.voronoi.Polygon';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.voronoi.Polygon.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voronoi.Polygon.prototype.toObject = function(opt_includeInstance) {
  return proto.voronoi.Polygon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voronoi.Polygon} msg The msg instance to transform.
 * @return {!Object}
 */
proto.voronoi.Polygon.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointList: jspb.Message.toObjectList(msg.getPointList(),
    proto.voronoi.LatLng.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voronoi.Polygon}
 */
proto.voronoi.Polygon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voronoi.Polygon;
  return proto.voronoi.Polygon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voronoi.Polygon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voronoi.Polygon}
 */
proto.voronoi.Polygon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.voronoi.LatLng;
      reader.readMessage(value,proto.voronoi.LatLng.deserializeBinaryFromReader);
      msg.addPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voronoi.Polygon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voronoi.Polygon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voronoi.Polygon} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.voronoi.Polygon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.voronoi.LatLng.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LatLng point = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.voronoi.LatLng>}
 */
proto.voronoi.Polygon.prototype.getPointList = function() {
  return /** @type{!Array.<!proto.voronoi.LatLng>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.voronoi.LatLng, 1));
};


/** @param {!Array.<!proto.voronoi.LatLng>} value */
proto.voronoi.Polygon.prototype.setPointList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.voronoi.LatLng=} opt_value
 * @param {number=} opt_index
 * @return {!proto.voronoi.LatLng}
 */
proto.voronoi.Polygon.prototype.addPoint = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.voronoi.LatLng, opt_index);
};


proto.voronoi.Polygon.prototype.clearPointList = function() {
  this.setPointList([]);
};


