/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.voronoi.User');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.voronoi.LatLng');
goog.require('proto.voronoi.Linear');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voronoi.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.voronoi.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.voronoi.User.displayName = 'proto.voronoi.User';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voronoi.User.prototype.toObject = function(opt_includeInstance) {
  return proto.voronoi.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voronoi.User} msg The msg instance to transform.
 * @return {!Object}
 */
proto.voronoi.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    totem: (f = msg.getTotem()) && proto.voronoi.LatLng.toObject(includeInstance, f),
    score: (f = msg.getScore()) && proto.voronoi.Linear.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voronoi.User}
 */
proto.voronoi.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voronoi.User;
  return proto.voronoi.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voronoi.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voronoi.User}
 */
proto.voronoi.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.voronoi.LatLng;
      reader.readMessage(value,proto.voronoi.LatLng.deserializeBinaryFromReader);
      msg.setTotem(value);
      break;
    case 4:
      var value = new proto.voronoi.Linear;
      reader.readMessage(value,proto.voronoi.Linear.deserializeBinaryFromReader);
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voronoi.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voronoi.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voronoi.User} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.voronoi.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTotem();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.voronoi.LatLng.serializeBinaryToWriter
    );
  }
  f = message.getScore();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.voronoi.Linear.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.voronoi.User.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.voronoi.User.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.voronoi.User.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.voronoi.User.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional LatLng totem = 3;
 * @return {?proto.voronoi.LatLng}
 */
proto.voronoi.User.prototype.getTotem = function() {
  return /** @type{?proto.voronoi.LatLng} */ (
    jspb.Message.getWrapperField(this, proto.voronoi.LatLng, 3));
};


/** @param {?proto.voronoi.LatLng|undefined} value */
proto.voronoi.User.prototype.setTotem = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.voronoi.User.prototype.clearTotem = function() {
  this.setTotem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.voronoi.User.prototype.hasTotem = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Linear score = 4;
 * @return {?proto.voronoi.Linear}
 */
proto.voronoi.User.prototype.getScore = function() {
  return /** @type{?proto.voronoi.Linear} */ (
    jspb.Message.getWrapperField(this, proto.voronoi.Linear, 4));
};


/** @param {?proto.voronoi.Linear|undefined} value */
proto.voronoi.User.prototype.setScore = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.voronoi.User.prototype.clearScore = function() {
  this.setScore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.voronoi.User.prototype.hasScore = function() {
  return jspb.Message.getField(this, 4) != null;
};


