/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.voronoi.Voronoi');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.voronoi.LatLng');
goog.require('proto.voronoi.Polygon');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.voronoi.Voronoi = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.voronoi.Voronoi.repeatedFields_, null);
};
goog.inherits(proto.voronoi.Voronoi, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.voronoi.Voronoi.displayName = 'proto.voronoi.Voronoi';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.voronoi.Voronoi.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.voronoi.Voronoi.prototype.toObject = function(opt_includeInstance) {
  return proto.voronoi.Voronoi.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.voronoi.Voronoi} msg The msg instance to transform.
 * @return {!Object}
 */
proto.voronoi.Voronoi.toObject = function(includeInstance, msg) {
  var f, obj = {
    totemList: jspb.Message.toObjectList(msg.getTotemList(),
    proto.voronoi.LatLng.toObject, includeInstance),
    userIdList: jspb.Message.getField(msg, 2),
    regionList: jspb.Message.toObjectList(msg.getRegionList(),
    proto.voronoi.Polygon.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.voronoi.Voronoi}
 */
proto.voronoi.Voronoi.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.voronoi.Voronoi;
  return proto.voronoi.Voronoi.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.voronoi.Voronoi} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.voronoi.Voronoi}
 */
proto.voronoi.Voronoi.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.voronoi.LatLng;
      reader.readMessage(value,proto.voronoi.LatLng.deserializeBinaryFromReader);
      msg.addTotem(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserId(value);
      break;
    case 3:
      var value = new proto.voronoi.Polygon;
      reader.readMessage(value,proto.voronoi.Polygon.deserializeBinaryFromReader);
      msg.addRegion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.voronoi.Voronoi.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.voronoi.Voronoi.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.voronoi.Voronoi} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.voronoi.Voronoi.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTotemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.voronoi.LatLng.serializeBinaryToWriter
    );
  }
  f = message.getUserIdList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getRegionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.voronoi.Polygon.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LatLng totem = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.voronoi.LatLng>}
 */
proto.voronoi.Voronoi.prototype.getTotemList = function() {
  return /** @type{!Array.<!proto.voronoi.LatLng>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.voronoi.LatLng, 1));
};


/** @param {!Array.<!proto.voronoi.LatLng>} value */
proto.voronoi.Voronoi.prototype.setTotemList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.voronoi.LatLng=} opt_value
 * @param {number=} opt_index
 * @return {!proto.voronoi.LatLng}
 */
proto.voronoi.Voronoi.prototype.addTotem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.voronoi.LatLng, opt_index);
};


proto.voronoi.Voronoi.prototype.clearTotemList = function() {
  this.setTotemList([]);
};


/**
 * repeated string user_id = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.voronoi.Voronoi.prototype.getUserIdList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 2));
};


/** @param {!Array.<string>} value */
proto.voronoi.Voronoi.prototype.setUserIdList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.voronoi.Voronoi.prototype.addUserId = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.voronoi.Voronoi.prototype.clearUserIdList = function() {
  this.setUserIdList([]);
};


/**
 * repeated Polygon region = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.voronoi.Polygon>}
 */
proto.voronoi.Voronoi.prototype.getRegionList = function() {
  return /** @type{!Array.<!proto.voronoi.Polygon>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.voronoi.Polygon, 3));
};


/** @param {!Array.<!proto.voronoi.Polygon>} value */
proto.voronoi.Voronoi.prototype.setRegionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.voronoi.Polygon=} opt_value
 * @param {number=} opt_index
 * @return {!proto.voronoi.Polygon}
 */
proto.voronoi.Voronoi.prototype.addRegion = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.voronoi.Polygon, opt_index);
};


proto.voronoi.Voronoi.prototype.clearRegionList = function() {
  this.setRegionList([]);
};


